# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
universal_binaries:
  - replace: true
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.Date={{.CommitDate}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
      - Goreleaser
      - Dockerfile
      - CI
      - '^test:'

sboms:
  - artifacts: archive

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    dependencies:
      - "bash"
    maintainer: "Peter Teich <mail@peter-teich.de>"
    vendor: "Peter Teich"
    homepage: "https://github.com/pteich"
    description: "Universal GUI for s3 compatible object storage systems."
    license: "MIT"

brews:
  - name: us3ui
    homepage: https://github.com/pteich/us3ui
    repository:
      owner: pteich
      name: homebrew-tap

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true