Website = "https://github.com/pteich/us3ui"

[Details]
  Icon = "Icon.png"
  Name = "Universal s3 GUI"
  ID = "de.peter-teich.us3ui"
  Version = "0.5.1"
  Build = 12

[LinuxAndBSD]
  GenericName = "Universal s3 GUI"
  Categories = ["Network"]
  Comment = "Browse s3 compatible storage systems and manage your files"
  Keywords = ["files", "cloud", "web"]
